service: videolyzer-test

provider:
    name: aws
    runtime: python3.6
    profile: ${file(../config.${self:provider.stage}.json):videolyzer.profile}
    iamRoleStatements:
        - Effect: "Allow"
          Action:
              - "rekognition:*"
          Resource: "*"

        - Effect: "Allow"
          Action:
              - "s3:GetObject"
          Resource:
              - Fn::Join:
                  - ''
                  - - ${self:custom.videosBucketArn}
                    - '/*'

functions:
    startProcessingVideo:
        handler: handler.start_processing_video
        events:
            - s3:
                bucket: ${file(../config.${self:provider.stage}.json):videolyzer.videos_bucket}
                event: s3:ObjectCreated:*
                rules:
                    - suffix: .mp4

custom:
    videosBucketArn:
        Fn::Join:
            - ':'
            - - arn
              - aws
              - s3
              - ''
              - ''
              - ${file(../config.${self:provider.stage}.json):videolyzer.videos_bucket}
